config/routes.rb
BookmarkingTool::Application.routes.draw do
  get "welcome/index"
  resources :bookmarks
  resources :sites

  root to: 'welcome#index'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
	belongs_to :site
	has_and_belongs_to_many :tags
end

app/models/bookmark_tag.rb
class BookmarkTag < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
	has_many :bookmarks
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
#  bookmarks_controller.rb 
#  Author: Danielle Fudger
#  Created: April, 2014
#
#  This controller creates the bookmarks and its relations to site and tags
#  it also includes the CRUD methods for the user to interact with the views.
  
class BookmarksController < ApplicationController

	def new
	end

	def index
		@bookmarks = Bookmark.all
	end

	def create
		siteDomain = params[:bookmark][:siteID]
		
		#Check if the site is already in the db, if not add it
		if(!(Site.find_by url: siteDomain))
			@site = Site.new(url: siteDomain)
			@site.save
		end
		
		#Save the id to the bookmark siteID param
		currSiteID = (Site.find_by url: siteDomain).id
		params[:bookmark][:siteID] = currSiteID

		#Add the bookmark and parameters to the database
		@bookmark = Bookmark.new(bookmark_params)
		@bookmark.save

		#Save relationship between site and this bookmark
		@site = Site.find_by url: siteDomain
		@site.bookmarks << @bookmark

		#Parse Tags
		tagsArray = (params[:bookmark][:tagList]).split(' ')

		#Add each tag to the table
		tagsArray.each do |c|
			#Check if tag already in db
			if(!(Tag.find_by title: c))
				@currTag = Tag.new(title: c)
				@currTag.save				
			end

			@bookmark.tags << (Tag.find_by title: c)
		end
	
		redirect_to @bookmark
	
	end

	def show
		@bookmark = Bookmark.find(params[:id])
	end


	private
 	def bookmark_params
 		params.require(:bookmark).permit(:url, :title, :description, :siteID)
  	end

end

app/controllers/sites_controller.rb
#  sites_controller.rb 
#  Author: Danielle Fudger
#  Created: April, 2014
#
#  This controller created the object that holds all the sites
  
class SitesController < ApplicationController

	def index
		@sites = Site.all
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/index.html.erb
<!-- 
   - Bookmarks/index.html.erb 
   - Author: Danielle Fudger
   - Created: April, 2014
   - 
   - This view allows the user to view all of the bookmarks within the database
   -->

<h1>All Bookmarks</h1>
 
<table>
  <!-- Headings -->
  <tr>
    <th>Title</th>
    <th>URL</th>
    <th></th>
  </tr>
 
  <!-- Data -->
  <% @bookmarks.each do |bookmark| %>
    <tr>
      <td><%= bookmark.title %></td>
      <td><%= bookmark.url %></td>
      <td><%= link_to 'Show', bookmark %></td>
    </tr>
  <% end %>
</table>

app/views/bookmarks/new.html.erb
<!-- 
   - Bookmark/new.html.erb 
   - Author: Danielle Fudger
   - Created: April, 2014
   - 
   - This view contains the form a user would fill to create a new bookmark.
   -->

<h1>New Bookmark</h1>

<p>Add a url and some information to save a bookmark to the site</p>
<br>

<!-- This is the form for creating a new bookmark -->
<%= form_for :bookmark, url: bookmarks_path do |f| %>
   <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

	<p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :tags %>
    <p>(Please separate tags by spaces)</p>
    <%= f.text_area :tagList %>
  </p>

  <p>
    <%= f.label :site %><br>
    <%= f.text_field :siteID %>
  </p>
 
  <%= f.submit 'Save Bookmark', :class => 'btn btn-primary' %>
<% end %>
<br>
<%= link_to 'Home', {controller: "welcome"}, :class => 'btn btn-primary' %>

app/views/bookmarks/show.html.erb
<!-- 
   - Bookmark/show.html.erb 
   - Author: Danielle Fudger
   - Created: April, 2014
   - 
   - This view displays information for an individual bookmark.
   -->

<h2><%= @bookmark.title %></h2>
<br>
<p>
  <%= @bookmark.description %>
</p>

<%= link_to @bookmark.url, 'http://'+@bookmark.url %>
<br><br>
<p>
  <strong>Tags:</strong>
 
  <% @bookmark.tags.each do |i| %>
  		
  		<%= i.title %>
  <% end %>
</p>
<br><br>
<%= link_to 'Home', {controller: "welcome"}, :class => 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookmarkingTool</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sites/index.html.erb
<!-- 
   - Sites/index.html.erb 
   - Author: Danielle Fudger
   - Created: April, 2014
   - Lists all of the sites, and their corresponding bookmarks.
   -->

<h1>Sites</h1>

<!-- Loop through each site in the db and display the bookmarks for each -->
<% @sites.each do |site| %>
	<h4><%= site.url %></h4>
	<ul>
    <% site.bookmarks.each do |i| %>
  	 <li>
      <%= link_to i.title, i %>
      
     </li>
    <% end %>
  </ul>
	<br>

<% end %>

<%= link_to 'Home', {controller: "welcome"}, :class => 'btn btn-primary' %>

app/views/welcome/index.html.erb
<!-- 
   - Welcome/index.html.erb 
   - Author: Danielle Fudger
   - Created: April, 2014
   - 
   - This is the homepage for the app. From here they can choose if they want to view or add a bookmark.
   -->

<h1>Bookmarking App</h1>
<h5>An AlphaSights Challenge</h5>
<br>

<%= link_to "Create a bookmark", new_bookmark_path, :class => 'btn btn-primary' %>
<%= link_to "View Sites", {controller: "sites"}, :class => 'btn btn-primary' %>